spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    caceh: false
    
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test